### PR TITLE
Adding support for aurora test network

### LINKED ISSUE #323: Deploy Ocean to Aurora Testnet (NEAR)
## TODOs
- [ ] Ensure there's a way to get OCEAN bridged over
- [ ] Multisig for OPF Wallet
- [ ] Deploy Ocean Smart Contracts
- [ ] Update ocean.js
- [ ] Deploy provider
- [ ] Add aquarius indexer
- [ ] Update graph
- [ ] Update market
- [ ] Update docs.oceanprotocol.com "supported networks"

## Motivation

Aurora is an Ethereum Virtual Machine created by the stellar team at the NEAR Protocol, delivering a turn-key solution for developers to operate their apps on an Ethereum-compatible, high-throughput, scalable and future-safe platform, with low transaction costs for their users. For more information, please refer to [Aurora docs](https://doc.aurora.dev/develop/networks)

## Advantages
- **Uses ETH** as a base currency
- Totally **Permissionless Bridge**
- **Bridging ERC20 tokens will come up soon**

image

## Faucet

- You can bridge any amount of [Ropsten ETH](https://faucet.ropsten.be/) to Aurora testnet through [Aurora bridge](https://testnet.aurora.dev/bridge). Just connect your Metamask with Ropsten and then you can bridge your tokens to the same address on Aurora. It takes around 2~4 mins to bridge the tokens as it waits for the transaction finality. Finally check out the The Aurora testnet metamask configuration below (Please make sure to use `ETH` as a **currency symbol**).

image

- Or you can use the Faucet but still doesn't have lots of liquidity [here](https://faucet.testnet.aurora.dev/)

For more details about bridging ETH check out this [tutorial](https://doc.aurora.dev/learn/connect/metamask).

### PR DESCRIPTION
**Pull request by 0x3bfc**
This is might be not the right way of integration but maybe you can keep the PR open for future support.

Adding support for deploying ocean contracts on [Aurora testnet](https://doc.aurora.dev/develop/networks)

- **Uses ETH**
- **Permissionless Bridge**
- **Bridging ERC20 tokens will come up soon**

image

## Deploy
```bash
yarn deploy:aurora
```
## Truffle console
```bash
truffle(aurora)> const factory = await DTFactory.deployed()
truffle(aurora)> const result = await factory.createToken("https://doc.aurora.dev", "Aurora DT", "ADT", 1000000)
truffle(aurora)> result.logs
[
  {
    blockNumber: 49401927,
    blockHash: '0x743bb3494775bf58a2cef85046a8c992d4cac061214be5304fab29b95d25fb68',
    transactionIndex: 0,
    transactionHash: '0xa3f506936c0ca537eddeb89f3187fca138b640d9da800c6f0b908881eef1dcfc',
    logIndex: 0,
    address: '0x079B62430541aa87EF5657FC6C5D8992B21131F8',
    removed: false,
    id: 'log_00adf600',
    event: 'InstanceDeployed',
    args: Result {
      '0': '0x35195C1d02bCdA6abF3D7867842268ee81FC4aDD',
      __length__: 1,
      instance: '0x35195C1d02bCdA6abF3D7867842268ee81FC4aDD'
    }
  },
  {
    blockNumber: 49401927,
    blockHash: '0x743bb3494775bf58a2cef85046a8c992d4cac061214be5304fab29b95d25fb68',
    transactionIndex: 0,
    transactionHash: '0xa3f506936c0ca537eddeb89f3187fca138b640d9da800c6f0b908881eef1dcfc',
    logIndex: 1,
    address: '0x079B62430541aa87EF5657FC6C5D8992B21131F8',
    removed: false,
    id: 'log_dcd6854c',
    event: 'TokenCreated',
    args: Result {
      '0': '0x35195C1d02bCdA6abF3D7867842268ee81FC4aDD',
      '1': '0x78E729B8c2ef2bd856754d65692c0a20d790C56E',
      '2': '0x04f9b5ed66d0a7f4700da5c2ba8b560ead433c2d32c98ab949a6928383ee80c6',
      __length__: 3,
      newTokenAddress: '0x35195C1d02bCdA6abF3D7867842268ee81FC4aDD',
      templateAddress: '0x78E729B8c2ef2bd856754d65692c0a20d790C56E',
      tokenName: '0x04f9b5ed66d0a7f4700da5c2ba8b560ead433c2d32c98ab949a6928383ee80c6'
    }
  },
  {
    blockNumber: 49401927,
    blockHash: '0x743bb3494775bf58a2cef85046a8c992d4cac061214be5304fab29b95d25fb68',
    transactionIndex: 0,
    transactionHash: '0xa3f506936c0ca537eddeb89f3187fca138b640d9da800c6f0b908881eef1dcfc',
    logIndex: 2,
    address: '0x079B62430541aa87EF5657FC6C5D8992B21131F8',
    removed: false,
    id: 'log_e4256a59',
    event: 'TokenRegistered',
    args: Result {
      '0': '0x35195C1d02bCdA6abF3D7867842268ee81FC4aDD',
      '1': 'Aurora DT',
      '2': 'ADT',
      '3': [BN],
      '4': '0x6A33382de9f73B846878a57500d055B981229ac4',
      '5': '0xa192d230b63e10044ca595ffb86414e4efda5d32e5c47cf46f2159c80ae5a7e5',
      __length__: 6,
      tokenAddress: '0x35195C1d02bCdA6abF3D7867842268ee81FC4aDD',
      tokenName: 'Aurora DT',
      tokenSymbol: 'ADT',
      tokenCap: [BN],
      registeredBy: '0x6A33382de9f73B846878a57500d055B981229ac4',
      blob: '0xa192d230b63e10044ca595ffb86414e4efda5d32e5c47cf46f2159c80ae5a7e5'
    }
  }
]
truffle(aurora)> const adtoken = await DataTokenTemplate.at('0x35195C1d02bCdA6abF3D7867842268ee81FC4aDD')
truffle(aurora)> await adtoken.minter()
'0x6A33382de9f73B846878a57500d055B981229ac4'
truffle(aurora)> await adtoken.name()
'Aurora DT'
```

closes #323

### CODE REVIEW

**Comment by alexcos20** [comment]
@0x3bfc - do you have a faucet url please?

**Comment by 0x3bfc** [comment]
> @0x3bfc - do you have a faucet url please?

We have two options:

- You can bridge any amount of [Ropsten ETH](https://faucet.ropsten.be/) to Aurora testnet through [Aurora bridge](https://testnet.aurora.dev/bridge). Just connect your Metamask with Ropsten and then you can bridge your tokens to the same address on Aurora. It takes around 2~4 mins to bridge the tokens as it waits for the transaction finality. Finally check out the The Aurora testnet metamask configuration below (Please make sure to use `ETH` as a **currency symbol**).



image

- Or you can use the Faucet but still doesn't have lots of liquidity [here](https://faucet.testnet.aurora.dev/)

**Comment by alexcos20** [comment]
Thanks.  I will have a full deployment (including Ocean Token test & OPFC Wallet) and I'm going to update this branch

**Comment by trentmc** [comment]
Could we also create a github issue, and link the PR to it, please? The github issue can briefly give background/motivation to do this. (And I'm sympathetic to this! I think NEAR is great.)

**Comment by 0x3bfc** [comment]
> Could we also create a github issue, and link the PR to it, please? The github issue can briefly give background/motivation to do this. (And I'm sympathetic to this! I think NEAR is great.)

https://github.com/oceanprotocol/contracts/issues/323

**Comment by trentmc** [comment]
> #323

Looks great, thanks!

**Pull request closed without merging**
