### PR TITLE
Release/v0.6.7

### PR DESCRIPTION
**Pull request by alexcos20**

### CODE REVIEW

**Comment by alexcos20** [comment]
packages already published in npm/pypi..  we should change this

**Comment by kremalicious** [comment]
I like the dialing back on yarn usage but if we do that then we also need to update all repo documentation around it, like main `README.md`, and the `/docs` documents like `RELEASE_PROCESS.md`. Basically replace all `yarn ...` with `npm run ...` and single `yarn` with `npm install` in any code instructions

**Comment by alexcos20** [comment]
yeah, I will open a new PR on that soon

**Comment by alexcos20** [comment]
@kremalicious ?

**Review by kremalicious — CHANGES_REQUESTED** [review]
great! Remaining thing: there's a `yarn-error.log` added to this PR, needs to be removed then should be good to go

**Comment by alexcos20** [comment]
sorry, I missed that :)

**Review by kremalicious — APPROVED** [review]

**Pull request merged**
