### PR TITLE
Add vesting wallet and splitter contracts

### LINKED ISSUE #743: Add Vesting wallet and Splitter contracts
Add Vesting wallet and Splitter contracts

### PR DESCRIPTION
**Pull request by trizin**
Fixes #743

Changes proposed in this PR:

- Add vesting wallet and splitter contracts.
- Update deploy script.

Main source is https://github.com/oceanprotocol/vw-cli , here we are just syncing the contracts.

### CODE REVIEW

**Review by trentmc — COMMENTED** [review]
Looks good to me. But I defer to Alex for a proper sign-off on this.

**Comment by alexcos20** [comment]
I will fix the errors

**Comment by alexcos20** [comment]
still WIP, depends on audit result

**Review by alexcos20 — APPROVED** [review]
lgtm

**Pull request merged**
