### PR TITLE
Rollback ve changes

### PR DESCRIPTION
**Pull request by trizin**
Changes proposed in this PR:

Rollback changes to ve contracts.

### CODE REVIEW

**Comment by trentmc** [comment]
Thanks. Could you show a diff of our code, and the original ve code? Perhaps right before doing the diff, replace CRV with OCEAN.

**Comment by trentmc** [comment]
> We made modifications in `veOCEAN.vy` and `veFeeDistributor.vy`. [Here is the `veFeeDistributor` diff](https://github.com/oceanprotocol/contracts/pull/696/files#diff-fb4c45801a2645fa89a11dcaa65f6397d3e35ebf73e7658fa3fa3cc3a9d232e5) [Here is the `veOCEAN` diff](https://github.com/oceanprotocol/contracts/pull/696/files#diff-d5b107dba519dce3b6e70043437673367fc679c262a823102900bdbb6a8a797d)

That's the diff between our code before the PR, and our code after the PR. (Or did I miss something?)

I'm interested to see the diff between our code after the PR, and Curve's code.

**Comment by alexcos20** [comment]
Looks like we are using different vyper versions for contracts:

-0.3.1 in  https://github.com/oceanprotocol/contracts/blob/rollback-ve-changes/contracts/ve/veDelegation.vy#L1
-0.2.15 in https://github.com/oceanprotocol/contracts/blob/rollback-ve-changes/contracts/ve/veDelegationProxy.vy#L1
-0.2.7 in https://github.com/oceanprotocol/contracts/blob/rollback-ve-changes/contracts/ve/veFeeDistributor.vy#L1
-0.2.4 in https://github.com/oceanprotocol/contracts/blob/rollback-ve-changes/contracts/ve/veOCEAN.vy#L1

Although, technically, is not an issue (we can download all those compilers), I do wonder if we can stick with one version for all contracts

**Review by alexcos20 — APPROVED** [review]
lgtm

**Pull request merged**
