### PR TITLE
add DF+VE, update deploy script

### LINKED ISSUE #677: add DF+VE, update deploy script
What to do here: support the contracts side of this [df-py oceanprotocol/df-py#32](https://github.com/oceanprotocol/df-issues/issues/82):

"Support DF & VE contracts in oceanprotocol/contracts, deployed to /barge, and exposed in /ocean-subgraph"

It also happens to support the barge side :)
https://github.com/oceanprotocol/contracts/pull/676#issuecomment-1192373935

### PR DESCRIPTION
**Pull request by alexcos20**
Fixes #677. That is, the contracts side of "DF & VE contracts in oceanprotocol/contracts, deployed to /barge, and exposed in /ocean-subgraph"

### CODE REVIEW

**Comment by alexcos20** [comment]
to use it, just do:

```
cd barge
export CONTRACTS_VERSION=dfve
./start_ocean.sh --no-dashboard
```

sample of generated address.json:
```
.....
"development": {
    "chainId": 8996,
    "Ocean": "0x2473f4F7bf40ed9310838edFCA6262C17A59DF64",
    "MockDAI": "0xaF6AaaA5B8D12F7d7dD4e2BE1d1B087544f585d0",
    "MockUSDC": "0x053aE1FeCdc2f391753E2Bf2AAe301E75CC0aac9",
    "OPFCommunityFeeCollector": "0x2fC1fd21cb222Dc180Ef817dE4c426fd9230b5A5",
    "startBlock": 5,
    "poolTemplate": "0x1e6d9207241DbDca82B0D9546490c97B24B1a9f6",
    "Router": "0xBb0911124E680D65358Ac46C5404D4dF01F03e80",
    "FixedPrice": "0x98b6901cE7C9fc65dBeeC98598136593EB7b4c6C",
    "Staking": "0x91EB42b164664cB28a09B0cF9651b404Ee105afA",
    "ERC20Template": {
      "1": "0x9C2a015129969c98E9A5BcBEb61A5F907FF5b629",
      "2": "0x611f28Ef25D778aFC5a0034Aea94297e2c215a42"
    },
    "ERC721Template": {
      "1": "0xe749E2f8482810b11B838Ae8c5eb69e54d610411"
    },
    "Dispenser": "0x8930D1F61Defb9CBD652136B4C3D93f19AC35678",
    "ERC721Factory": "0x312213d6f6b5FCF9F56B7B8946A6C727Bf4Bc21f",
    "DFRewards": "0x726baA2f854A3BEC2378a707AeB38c9d933Ebad6",
    "DFStrategyV1": "0xF152cF3c67dFD41a317eAe8fAc0e1e8E98724A13",
    "veAllocate": "0xfeA10BBb093d7fcb1EDf575Aa7e28d37b9DcFcE9",
    "veOCEAN": "0xEEE56e2a630DD29F9A628d618E58bb173911F393",
    "veDelegation": "0x85cCa2B01adddCA8Df221e6027EE0D7716224202",
    "veFeeDistributor": "0x645439117eB378a6d35148452E287a038666Ed67",
    "veDelegationProxy": "0x3a3926f3f88F1eE05164404f93FDb3887cbE8e35"
  }
}
```

**Comment by trentmc** [comment]
> to use it, just do: ...

This looks like a practical, viable approach. +1 :)

All go to merge? 

Then we can start using it in ocean-subgraph, and after that df-py. Thanks!

**Comment by alexcos20** [comment]
let me clean it up first

**Review by trentmc — APPROVED** [review]

**Comment by trentmc** [comment]
🔥

**Pull request merged**
